function next_state = predict(x,y,z,dx,dy,dz,ddx,ddy,ddz,rx,ry,rz,drx,dry,drz,ddrx,ddry,ddrz,L,dt)
%PREDICT
%    NEXT_STATE = PREDICT(X,Y,Z,DX,DY,DZ,DDX,DDY,DDZ,RX,RY,RZ,DRX,DRY,DRZ,DDRX,DDRY,DDRZ,L,DT)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    22-Oct-2021 22:03:33

next_state = [x+dt.*dx;y+dt.*dy;z+dt.*dz;dx+ddx.*dt;dy+ddy.*dt;dz+ddz.*dt;ddx;ddy;ddz;rx+drx.*dt;ry+dry.*dt;rz+drz.*dt;drx+ddrx.*dt;dry+ddry.*dt;drz+ddrz.*dt;ddrx;ddry;ddrz];
