function hj_s2 = update_hjs2(x,y,z,dx,dy,dz,ddx,ddy,ddz,rx,ry,rz,drx,dry,drz,ddrx,ddry,ddrz,L,dt)
%UPDATE_HJS2
%    HJ_S2 = UPDATE_HJS2(X,Y,Z,DX,DY,DZ,DDX,DDY,DDZ,RX,RY,RZ,DRX,DRY,DRZ,DDRX,DDRY,DDRZ,L,DT)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    25-Oct-2021 21:46:20

t2 = cos(rx);
t3 = cos(ry);
t4 = cos(rz);
t5 = sin(rx);
t6 = sin(ry);
t7 = sin(rz);
hj_s2 = reshape([1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-L.*(t5.*t7+t2.*t4.*t6),L.*(t4.*t5-t2.*t6.*t7),-L.*t2.*t3,-L.*t3.*t4.*t5,-L.*t3.*t5.*t7,L.*t5.*t6,L.*(t2.*t4+t5.*t6.*t7),L.*(t2.*t7-t4.*t5.*t6),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[3,18]);
