function h_s2 = update_hs2(x,y,z,dx,dy,dz,ddx,ddy,ddz,rx,ry,rz,drx,dry,drz,ddrx,ddry,ddrz,L,dt)
%UPDATE_HS2
%    H_S2 = UPDATE_HS2(X,Y,Z,DX,DY,DZ,DDX,DDY,DDZ,RX,RY,RZ,DRX,DRY,DRZ,DDRX,DDRY,DDRZ,L,DT)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    25-Oct-2021 21:46:20

t2 = cos(rx);
t3 = cos(rz);
t4 = sin(rx);
t5 = sin(ry);
t6 = sin(rz);
h_s2 = [x+L.*(t2.*t6-t3.*t4.*t5);y-L.*(t2.*t3+t4.*t5.*t6);z-L.*t4.*cos(ry)];
