function h_s3 = update_hs3(x,y,z,dx,dy,dz,ddx,ddy,ddz,rx,ry,rz,drx,dry,drz,ddrx,ddry,ddrz,L,dt)
%UPDATE_HS3
%    H_S3 = UPDATE_HS3(X,Y,Z,DX,DY,DZ,DDX,DDY,DDZ,RX,RY,RZ,DRX,DRY,DRZ,DDRX,DDRY,DDRZ,L,DT)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    25-Oct-2021 21:46:20

t2 = cos(ry);
h_s3 = [x+L.*t2.*cos(rz);y+L.*t2.*sin(rz);z-L.*sin(ry)];
